"""Scan verdict payloads (Phase 4.4 — food-drug interaction & severity scoring)."""

from __future__ import annotations

import datetime as dt

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.schemas.nudge import NudgeOut


class ScanVerdictIn(BaseModel):
    """A product's decoded ingredients (from Phase 4.1 / 4.2, optionally already
    passed through 4.3) plus its per-100 g nutriments. The user's conditions,
    allergies and active medications are read server-side from the JWT — never
    sent by the client."""

    ingredients: list[str] = Field(default_factory=list, max_length=400)
    nutriments: dict[str, float] = Field(
        default_factory=dict,
        description="Normalised per-100 g nutriments (same keys as GET /products/{barcode}).",
    )
    barcode: str | None = Field(default=None, max_length=14)
    product_name: str | None = Field(default=None, max_length=200)

    @field_validator("ingredients")
    @classmethod
    def _cap_each(cls, v: list[str]) -> list[str]:
        return [str(x)[:200] for x in v if str(x).strip()]

    @field_validator("nutriments")
    @classmethod
    def _sane_nutriments(cls, v: dict[str, float]) -> dict[str, float]:
        """Bound the map so a malformed / hostile client can't push an
        unbounded blob or non-finite values into the scoring engine."""
        import math

        out: dict[str, float] = {}
        for k, val in v.items():
            if len(out) >= 40:
                break
            key = str(k).strip()[:60]
            if not key or not math.isfinite(val):
                continue
            out[key] = max(-1_000.0, min(1_000_000.0, float(val)))
        return out

    @field_validator("barcode")
    @classmethod
    def _barcode_digits(cls, v: str | None) -> str | None:
        if v is None:
            return None
        v = v.strip()
        if v and not (v.isdigit() and 8 <= len(v) <= 14):
            raise ValueError("barcode must be 8–14 digits")
        return v or None


class VerdictReasonOut(BaseModel):
    kind: str = Field(
        description="allergen | drug_interaction | condition_ceiling | "
        "condition_compound | poor_fit | unverified | clear"
    )
    severity: str = Field(description="high | moderate | low | info")
    points: int = Field(description="Score deducted for this factor (0 for a hard stop / info).")
    title: str
    detail: str | None = None
    factor: str | None = Field(
        default=None,
        description="The recurring risk_compound this reason is about (sodium, …). "
        "Phase 5.3 groups repeat scans by this.",
    )


class MedMatchOut(BaseModel):
    name: str
    drug_classes: list[str] = Field(default_factory=list)
    identified: bool


class ScanVerdictOut(BaseModel):
    score: int = Field(ge=0, le=100)
    tier: str = Field(
        description="safe (>=70) | caution (>=45) | avoid — the exact Phase 2.1 thresholds"
    )
    hard_stop: bool = Field(
        description="True when an allergen match forced 'avoid' regardless of score."
    )
    reasons: list[VerdictReasonOut] = Field(
        default_factory=list,
        description="Plain-language, most-severe-first list of what drove the verdict.",
    )
    medications: list[MedMatchOut] = Field(default_factory=list)
    risk_compounds: dict[str, float] = Field(default_factory=dict)
    unverified: list[str] = Field(default_factory=list)
    unverified_count: int = 0
    lifestyle_applied: list[str] = Field(
        default_factory=list,
        description="Lifestyle multipliers applied to nutrition deductions "
        "(Step 7b), e.g. ['stress 22/100 ×1.25 on added_sugar']. Empty when "
        "the lifestyle profile is unset or every relevant dimension is fine.",
    )
    nudge: NudgeOut | None = Field(
        default=None,
        description="A nudge generated by THIS scan (Phase 5.3), if the 14-day "
        "pattern threshold was just crossed — otherwise poll GET /nudges.",
    )


# --------------------------------------------------------------------------- #
# diet log (Phase 5.1) — GET /history
# --------------------------------------------------------------------------- #
class HistoryReason(BaseModel):
    kind: str
    severity: str
    title: str
    factor: str | None = None  # recurring risk_compound (Phase 5.3 grouping)


class ScanHistoryItem(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    product_name: str
    score: int
    tier: str
    hard_stop: bool = False
    key_reasons: list[HistoryReason] = Field(default_factory=list)
    scanned_at: dt.datetime

    @field_validator("id", mode="before")
    @classmethod
    def _stringify_id(cls, v: object) -> str:
        return str(v)


class ScanHistoryPage(BaseModel):
    items: list[ScanHistoryItem]
    total: int = Field(description="Total rows for this user.")
    limit: int
    offset: int
    has_more: bool
